# Generated by Django 5.0.7 on 2024-09-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Entidades',
            fields=[
                ('idEntidad', models.AutoField(primary_key=True, serialize=False)),
                ('entidad', models.CharField(max_length=330)),
            ],
        ),
    ]
