# Generated by Django 5.0.7 on 2024-09-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CargoUsuario',
            fields=[
                ('idCargo', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cargos',
            new_name='CargoAdmin',
        ),
    ]
