# Generated by Django 5.0.7 on 2024-09-21 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_app', '0002_cargousuario_rename_cargos_cargoadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('idTipoDocumento', models.AutoField(primary_key=True, serialize=False)),
                ('TipoDocumento', models.CharField(max_length=255)),
            ],
        ),
    ]
