# Generated by Django 5.0.7 on 2024-09-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_app', '0003_tipodocumento'),
        ('base_app', '0003_administradores_cargo_usuarios_cargo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entidades',
            new_name='Entidad',
        ),
    ]
