# Generated by Django 5.0.7 on 2024-09-22 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0001_initial'),
        ('base_app', '0006_remove_administrador_cargo_administrador_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='edicionusuario',
            name='admin',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base_app.administrador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='edicionusuario',
            name='idEdicion',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='edicionusuario',
            name='usuario_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='base_app.usuario'),
        ),
    ]
