# Generated by Django 5.0.7 on 2024-09-22 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_edicionusuario_admin_edicionusuario_idedicion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EdicionUsuario',
        ),
    ]
