# Generated by Django 5.0.7 on 2024-09-22 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_app', '0003_delete_edicionusuario'),
        ('autenticacion_app', '0006_rename_cargousuario_cargo'),
        ('base_app', '0007_alter_administrador_correo_alter_usuario_correo'),
    ]

    operations = [
        migrations.CreateModel(
            name='EdicionUsuario',
            fields=[
                ('numDocumento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=320)),
                ('idEdicion', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('oldTipoDocumento', models.CharField(max_length=50)),
                ('oldNumDocumento', models.CharField(max_length=100)),
                ('oldNombre', models.CharField(max_length=255)),
                ('oldApellido', models.CharField(max_length=255)),
                ('oldEntidad', models.CharField(max_length=100)),
                ('oldCorreo', models.CharField(max_length=320)),
                ('cargo', models.CharField(max_length=255)),
                ('oldCargo', models.CharField(max_length=255)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.administrador')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.entidad')),
                ('tipoDocumento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.tipodocumento')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
