# Generated by Django 5.0.7 on 2024-09-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edicionusuario',
            name='entidad',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='edicionusuario',
            name='tipoDocumento',
            field=models.CharField(max_length=50),
        ),
    ]
