# Generated by Django 5.0.7 on 2024-09-22 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_alter_edicionusuario_entidad_and_more'),
        ('base_app', '0008_usuario_diaregistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EliminacionUsuario',
            fields=[
                ('numDocumento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=320)),
                ('idEliminacion', models.AutoField(primary_key=True, serialize=False)),
                ('dia', models.DateField(auto_now=True)),
                ('hora', models.TimeField(auto_now=True)),
                ('tipoDocumento', models.CharField(max_length=50)),
                ('entidad', models.CharField(max_length=100)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.administrador')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
