# Generated by Django 5.0.7 on 2024-09-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autenticacion_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administradores',
            fields=[
                ('tipoDocumento', models.CharField(max_length=255)),
                ('numDocumento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('idAdmin', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=255)),
                ('contraseña', models.CharField(max_length=255)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.cargos')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.entidades')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('tipoDocumento', models.CharField(max_length=255)),
                ('numDocumento', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('apellido', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.cargos')),
                ('entidad', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.entidades')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
