# Generated by Django 5.0.7 on 2024-09-21 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion_app', '0003_tipodocumento'),
        ('base_app', '0002_remove_administradores_cargo_remove_usuarios_cargo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administradores',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.cargoadmin'),
        ),
        migrations.AddField(
            model_name='usuarios',
            name='cargo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.cargousuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administradores',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='tipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.tipodocumento'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='correo',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='tipoDocumento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='autenticacion_app.tipodocumento'),
        ),
    ]
