# Generated by Django 5.0.7 on 2024-09-21 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_rename_administradores_administrador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='administrador',
            name='usuario',
        ),
        migrations.AddField(
            model_name='administrador',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='admin_profile', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
