# Generated by Django 5.0.7 on 2024-09-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_remove_administrador_contraseña_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='cargo',
        ),
        migrations.AddField(
            model_name='administrador',
            name='superAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
