# Generated by Django 5.0.7 on 2024-09-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_alter_administrador_correo_alter_usuario_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='diaRegistro',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
