# Generated by Django 5.0.7 on 2024-09-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDispositivo',
            fields=[
                ('idTipoDisp', models.AutoField(primary_key=True, serialize=False)),
                ('tipoDisp', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('idRegistro', models.AutoField(primary_key=True, serialize=False)),
                ('horaIngreso', models.TimeField()),
                ('horaSalida', models.TimeField()),
                ('dispositivos', models.JSONField(blank=True)),
                ('dia', models.DateField(auto_now=True)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivos',
            fields=[
                ('idDispositivo', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=330)),
                ('idUsuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base_app.usuarios')),
                ('idTipoDisp', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='registro_app.tipodispositivo')),
            ],
        ),
    ]
