# Generated by Django 5.0.7 on 2024-09-21 01:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivos',
            name='idTipoDisp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro_app.tipodispositivo'),
        ),
        migrations.AlterField(
            model_name='registros',
            name='horaSalida',
            field=models.TimeField(blank=True),
        ),
    ]
