# Generated by Django 5.0.7 on 2024-09-21 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_rename_administradores_administrador_and_more'),
        ('registro_app', '0002_alter_dispositivos_idtipodisp_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dispositivos',
            new_name='Dispositivo',
        ),
        migrations.RenameModel(
            old_name='Registros',
            new_name='Registro',
        ),
    ]
